---
# Install Morgan Server

- name: Copy Server binary
  copy:
    src: files/morgan
    dest: /usr/local/bin/morgan
    owner: root
    group: root
    mode: 0755

- name: Copy Server startup script
  copy:
    src: files/server.sh
    dest: /usr/local/bin/server.sh
    owner: root
    group: root
    mode: 0755

- name: Copy Server Consul service json file
  copy:
    src: files/server.json
    dest: /etc/consul.d/
    owner: consul
    group: consul
    mode: 0755

- name: Copy Server service script
  copy:
    src: files/server.service
    dest: /etc/systemd/system/server.service
    owner: root
    group: root
    mode: 0644

- name: Enable Server service
  shell: |
    set -e
    systemctl enable server
    systemctl start server
    exit 0
