---
# Install Grafana Server

- name: Install Grafana deb package 
  apt:
    deb: https://dl.grafana.com/oss/release/grafana_6.1.6_amd64.deb
  become: yes
  become_user: root
  become_method: sudo       

- name: Copy grafana.ini
  copy:
    src: files/grafana.ini
    dest: "/etc/grafana"
    owner: "grafana"
    group: "grafana"
    mode: 0640    
  become: yes
  become_user: root
  become_method: sudo
  notify: restart grafana

- name: Copy ldap.toml
  copy:
    src: files/ldap.toml
    dest: "/etc/grafana"
    owner: "grafana"
    group: "grafana"
    mode: 0640    
  become: yes
  become_user: root
  become_method: sudo
  notify: restart grafana

- name: Enable and start grafana service
  service:
    name: grafana-server
    state: started
    enabled: yes      
  become: yes
  become_user: root
  become_method: sudo

- name: Copy Grafana service definition
  copy:
    src: files/grafana.tpl
    dest: /etc/consul.d/grafana.tpl
    owner: consul
    group: consul
    mode: 0755
  become: yes
  become_user: root
  become_method: sudo
    
- name: Update Grafana bind address and restart consul to register Grafana as a service
  shell: |
    set -e
    cd /etc/consul.d/
    bind_addr=$(ifconfig | grep eth1 -A 1 | grep inet | awk '{ print $2 }')
    cat grafana.tpl | sed 's/__ip__/'"${bind_addr}"'/g' > grafana.json
    chown consul:consul grafana.json
    /usr/local/bin/consul reload
    exit 0    
  become: yes
  become_user: root
  become_method: sudo
