---

# -------------------------------------------------------------------------------------
# Fabio
# -------------------------------------------------------------------------------------
- name: fabio
  hosts: "{{ target }}" 
  vars: 
    version: "1.5.12" 
    go_version: "1.13.1"  
  user: "{{ user }}"
  become: yes
  become_user: root
  become_method: sudo  
  any_errors_fatal: true
  roles:
    - role: fabio    
  tags:
    - fabio

# Aminate fabio using Ansible

# We need -E to carry the injected environment variables into aminator call

# sudo -E aminate -n fabio -e ec2_ansible_linux -B ${base_ami} --extra-vars "target=all consul_cluster_hostname=consul.example.io" \
# --enhanced-networking \
# --ena-networking \
# --arch x86_64 \
# --provisioner-ebs-type gp2 \
# --register-ebs-type gp2 \
# --vm-type hvm \
# --partition 1 \
# fabio.yml    