---

# -------------------------------------------------------------------------------------
# Golang
# -------------------------------------------------------------------------------------
- name: go
  hosts: "{{ target }}"
  vars: 
    version: "1.13.5"
  user: "{{ user }}"
  roles:
    - role: go