---

# -------------------------------------------------------------------------------------
# Grafana
# -------------------------------------------------------------------------------------
- name: grafana
  hosts: "{{ target }}"
  user: "{{ user }}"
  roles:
  - role: grafana
  tags:
    - grafana
