---

# -------------------------------------------------------------------------------------
# Nomad
# -------------------------------------------------------------------------------------
- name: nomad
  hosts: "{{ target }}"
  user: "{{ user }}"
  become: yes
  become_user: root
  become_method: sudo  
  any_errors_fatal: true
  vars: 
    version: "0.11.3"
    nodes: 
      - "tmt-vm4.7onetella.net"
      - "tmt-vm5.7onetella.net"
      - "tmt-vm6.7onetella.net"  
  roles:
    - role: nomad-agent