---

# -------------------------------------------------------------------------------------
# password
# -------------------------------------------------------------------------------------
- name: password
  hosts: "{{ target }}"
  become: yes
  become_user: root
  become_method: sudo  
  any_errors_fatal: true
  roles:
    - password
  tags:
    - password
